name: Sign Release

on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: windows-latest

    env:
      SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
      SIGNPATH_ORGANIZATION_ID: ${{ secrets.SIGNPATH_ORGANIZATION_ID }}
      SIGNPATH_PROJECT_SLUG: ${{ secrets.SIGNPATH_PROJECT_SLUG }}
      SIGNPATH_SIGNING_POLICY: ${{ secrets.SIGNPATH_SIGNING_POLICY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build project
        run: msbuild "visual studio\suspend.sln" /p:Configuration=Release /p:Platform=x64 /p:ClCompileOptimization=MaxSpeed

      - name: Prepare ZIP
        run: |
          mkdir input
          copy "visual studio\x64\Release\suspend.exe" "input\suspend.exe"
          Compress-Archive -Path "input\suspend.exe" -DestinationPath "input/Spencer-Macro-Utilities.zip"

      - name: Upload unsigned ZIP for signing
        id: upload-artifact-step
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-zip
          path: input/Spencer-Macro-Utilities.zip

      - name: Submit signing request to SignPath
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          organization-id: ${{ secrets.SIGNPATH_ORGANIZATION_ID }}
          project-slug: ${{ secrets.SIGNPATH_PROJECT_SLUG }}
          signing-policy-slug: ${{ secrets.SIGNPATH_SIGNING_POLICY }}
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          github-artifact-id: ${{ steps.upload-artifact-step.outputs.artifact-id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-completion: true
          artifact-configuration-slug: initial

      - name: Upload signed artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-release
          path: signpath-artifacts/**
